=== Cross-bit/NPRG036/HW3/3/xml/schemas/schema-3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="https://www.w3.org/2009/01/xml.xsd" />
	
	<xs:element name="ZoomURI" type="xs:anyURI" />
	<xs:attribute name="ID" type="xs:anyURI" />
	
	<xs:element name="Code">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[a-zA-Z0-9]+" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="Lesson">
		<xs:complexType>
			<xs:all>
				<xs:element ref="ZoomURI" />
				<xs:element ref="Code" />
			</xs:all>
            <xs:attribute ref="ID" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Subject">
		<xs:complexType>
			<xs:all>
				<xs:element name="Name">
                  <xs:complexType>
                    <xs:simpleContent>
                      <xs:extension base="xs:string">
                        <xs:attribute ref="xml:lang" use="required" />
                      </xs:extension>
                    </xs:simpleContent>
                  </xs:complexType>                  
				</xs:element>
				<xs:element name="IsTaught">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Lesson" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
            <xs:attribute ref="ID" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Subjects">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Subject" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Cross-bit/NPRG036/HW3/3/xml/schemas/data-3.xml
<?xml version="1.0" encoding="utf-8"?>
<Subjects
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schemas/schema-3.xsd"
>


    <Subject ID="http://example.org/data/subjects/mt">
        <Name xml:lang="cs">Matematika</Name>
        <IsTaught>
            <Lesson ID="http://example.org/data/lessons/TH0855S7">
				<ZoomURI>https://zoom.com/TH0855S7</ZoomURI>
				<Code>TH0855S7</Code>
			</Lesson>
			<Lesson ID="http://example.org/data/lessons/TH0855S6">
				<ZoomURI>https://zoom.com/TH0855S6</ZoomURI>
				<Code>TH0855S6</Code>
			</Lesson>
        </IsTaught>
    </Subject>

    <Subject ID="http://example.org/data/subjects/en">
        <Name xml:lang="cs">Angliƒçtina</Name>
        <IsTaught>
            <Lesson ID="http://example.org/data/lessons/MO0800S7">
				<ZoomURI>https://zoom.com/MO0800S7</ZoomURI>
				<Code>MO0800S7</Code>
			</Lesson>
			<Lesson ID="http://example.org/data/lessons/FR1000S9">
				<ZoomURI>https://zoom.com/FR1000S9</ZoomURI>
				<Code>FR1000S9</Code>
			</Lesson>
        </IsTaught>
    </Subject>

    <Subject ID="http://example.org/data/subjects/ps">
        <Name xml:lang="cs">Fyzika</Name>
        <IsTaught>
            <Lesson ID="http://example.org/data/lessons/FR1000S6">
				<ZoomURI>https://zoom.com/FR1000S6</ZoomURI>
				<Code>FR1000S6</Code>
			</Lesson>
        </IsTaught>
    </Subject>




</Subjects>
