=== Cross-bit/NPRG036/HW3/3/xml/schemas/schema-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="TimeSlotBeginning" type="xs:time" />
	<xs:element name="TimeSlotEnd" type="xs:time" />
	<xs:element name="ZoomURI" type="xs:anyURI" />
	<xs:attribute name="ID" type="xs:anyURI" />
	
	<xs:element name="Code">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[a-zA-Z0-9]+" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:simpleType name="DayOfWeek">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Monday" />
			<xs:enumeration value="Tuesday" />
			<xs:enumeration value="Wednesday" />
			<xs:enumeration value="Thursday" />
			<xs:enumeration value="Friday" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="Lesson">
		<xs:complexType>
			<xs:attribute ref="ID" use="required" />
			<xs:all>
				<xs:element ref="ZoomURI" />
				<xs:element ref="Code" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="TimeSlot">
		<xs:complexType>
			<xs:attribute ref="ID" use="required" />
			<xs:all>
				<xs:element ref="TimeSlotBeginning" />
				<xs:element ref="TimeSlotEnd" />
				<xs:element ref="DayOfWeek" />
				<xs:element name="TakesTime">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Lesson" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="TimeSlots">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="TimeSlot" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Cross-bit/NPRG036/HW3/3/xml/data/data-1.xml
<?xml version="1.0" encoding="utf-8"?>
<TimeSlots
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../schemas/schema-1.xsd" >
    <TimeSlot ID="http://example.org/data/timeslots/MO0800" >
        <TimeSlotBeginning>08:00:00</TimeSlotBeginning>
        <TimeSlotEnd>08:45:00</TimeSlotEnd>
        <DayOfWeek>Monday</DayOfWeek>
        <TakesTime>
            <Lesson ID="http://example.org/data/lessons/MO0800S7">
                <ZoomURI>https://zoom.com/MO0800S7</ZoomURI>
                <Code>MO0800S7</Code>
            </Lesson>
        </TakesTime>
    </TimeSlot>

    <TimeSlot ID="http://example.org/data/timeslots/TH0855" >
        <TimeSlotBeginning>08:55:00</TimeSlotBeginning>
        <TimeSlotEnd>09:40:00</TimeSlotEnd>
        <DayOfWeek>Thursday</DayOfWeek>
        <TakesTime>
            <Lesson ID="http://example.org/data/lessons/TH0855S6">
                <ZoomURI>https://zoom.com/TH0855S6</ZoomURI>
                <Code>TH0855S6</Code>
            </Lesson>
            <Lesson ID="http://example.org/data/lessons/TH0855S7">
                <ZoomURI>https://zoom.com/TH0855S7</ZoomURI>
                <Code>TH0855S7</Code>
            </Lesson>
        </TakesTime>
    </TimeSlot>
    
    <TimeSlot ID="http://example.org/data/timeslots/FR1000" >
        <TimeSlotBeginning>10:00:00</TimeSlotBeginning>
        <TimeSlotEnd>10:45:00</TimeSlotEnd>
        <DayOfWeek>Friday</DayOfWeek>
        <TakesTime>
            <Lesson ID="http://example.org/data/lessons/FR1000S9">
                <ZoomURI>https://zoom.com/FR1000S9</ZoomURI>
                <Code>FR1000S9</Code>
            </Lesson>
            <Lesson ID="http://example.org/data/lessons/FR1000S6">
                <ZoomURI>https://zoom.com/FR1000S6</ZoomURI>
                <Code>FR1000S6</Code>
            </Lesson>
        </TakesTime>
    </TimeSlot>
</TimeSlots>
