=== Cross-bit/NPRG036/HW3/3/xml/schemas/schema-4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:import namespace="http://www.w3.org/XML/1998/namespace"
			schemaLocation="https://www.w3.org/2009/01/xml.xsd" />

	<xs:attribute name="ID" type="xs:anyURI" />
	<xs:element name="Code">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[a-zA-Z0-9]*"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="Subject">
		<xs:complexType>
			<xs:attribute ref="ID" use="required" />
			<xs:all>
				<xs:element ref="Code" />
				<xs:element name="Name" type="xs:string" >
					<xs:attribute ref="xml:lang" use="required" />
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Class">
		<xs:complexType>
			<xs:attribute ref="ID" use="required" />
			<xs:all>
				<xs:element name="ClassYear" type="xs:integer" />
				<xs:element name="ClassCode" ref="Code" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Teacher">
		<xs:complexType>
			<xs:attribute ref="ID" use="required" />
			<xs:all>
				<xs:element ref="Code" />
				<xs:element name="Name" type="xs:string">
					<xs:attribute ref="xml:lang" use="required" />
				</xs:element>
				<xs:element name="experience" type="xs:integer" />
				<xs:element name="classTeacher" ref="Class" />
				<xs:element name="Subjects" >
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Subject" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Teachers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Teacher" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Cross-bit/NPRG036/HW3/3/xml/data/data-4.xml
<?xml version="1.0" encoding="utf-8"?>
<Teachers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/schema-4.xsd">
	<Teacher ID="http://example.org/data/teachers/muk">
		<Code>muk</Code>
		<Name xml:lang="cs">Vladimír Mukvald</Name>
		<Experience>5</Experience>
		<ClassTeacher ID="http://example.org/data/classes/6A">
			<ClassYear>6</ClassYear>
			<ClassCode>A</ClassCode>
		</ClassTeacher>
		<Subjects>
			<Subject ID="http://example.org/data/subjects/Math">
				<Code>mt</Code>
				<Name xml:lang="cs">Matematika</Name>
			</Subject>
		</Subjects>
	</Teacher>
	<Teacher ID="http://example.org/data/teachers/pel">
		<Code>pel</Code>
		<Name xml:lang="cs">Jaroslav Pelikán</Name>
		<Experience>3</Experience>
		<ClassTeacher ID="http://example.org/data/classes/6B">
			<ClassYear>6</ClassYear>
			<ClassCode>B</ClassCode>
		</ClassTeacher>
		<Subjects>
			<Subject ID="http://example.org/data/subjects/Math">
				<Code>mt</Code>
				<Name xml:lang="cs">Matematika</Name>
			</Subject>
			<Subject ID="http://example.org/data/subjects/Physics">
				<Code>ps</Code>
				<Name xml:lang="cs">Fyzika</Name>
			</Subject>
		</Subjects>
	</Teacher>
	<Teacher ID="http://example.org/data/teachers/svo">
		<Code>svo</Code>
		<Name xml:lang="cs">Patrik Svoboda</Name>
		<Experience>2</Experience>
		<ClassTeacher ID="http://example.org/data/classes/4C">
			<ClassYear>4/ClassYear>
			<ClassCode>C</ClassCode>
		</ClassTeacher>
		<Subjects>
			<Subject ID="http://example.org/data/subjects/English">
				<Code>en</Code>
				<Name xml:lang="cs">Angličtina</Name>
			</Subject>
		</Subjects>
	</Teacher>
</Teachers>
