=== Cross-bit/NPRG036/HW3/3/xml/schema-5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ZoomURI" type="xs:anyURI" />
    	<xs:attribute name="ID" type="xs:anyURI" />
	
	<xs:element name="code">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[a-z0-9]*"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

    	<xs:element name="AcademicalYear">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{4}[/]\d{4}"/>
                <xs:length value="9"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="Lesson">
		<xs:complexType>
			<xs:attribute ref="ID" use="required" />
			<xs:all>
				<xs:element ref="ZoomURI" />
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:element name="Student">
		<xs:complexType>
			<xs:attribute ref="ID" use="required" />
			<xs:all>
				<xs:element name="name" type="xs:string" />
				<xs:element name="Nickname" type="xs:string" maxOccurs="unbounded"/>
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:element name="Class">
		<xs:complexType>
			<xs:attribute ref="ID" use="required" />
			<xs:all>
				<xs:element name="ClassYear" type="xs:integer" />
				<xs:element name="ClassCode" ref="code" />
                <xs:element name="BelongsTo">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Student" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>  
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:element name="Timetable">
		<xs:complexType>
			<xs:attribute ref="ID" use="required" />
			<xs:all>
				<xs:element ref="AcademicalYear" />
                <xs:element name="TimetableVersion" type="xs:float" />
            	<xs:element name="PlannedLesson">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Lesson" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>    
                <xs:element name="BelongingClass">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Class" maxOccurs="1" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>  
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:element name="Timetables">
		<xs:complexType>
			<xs:attribute ref="ID" use="required" />
			<xs:sequence>
				<xs:element ref="Timetable" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Cross-bit/NPRG036/HW3/3/xml/data/data-5.xml
<?xml version="1.0" encoding="utf-8"?>
<Timetables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/schema-5.xsd">
	<Timetable ID="http://example.org/data/timetables/20216A15" >
		<AcademicalYear>2020/2021</AcademicalYear>
		<TimetableVersion>1.5</TimetableVersion>
		<PlannedLesson>
			<Lesson ID="http://example.org/data/lessons/TH0855S6">
				<ZoomURI>https://zoom.com/TH0855S6</ZoomURI>
				<LessonCode>TH0855S6</LessonCode>
			</Lesson>
		</PlannedLesson>
		<BelongingClass>
			<Class ID="http://example.org/data/classes/6A">
                <ClassYear>6</ClassYear>
				<ClassCode>A</ClassCode>
				<BelongsTo>
					<Student ID="http://example.org/data/students/kovpe">
						<Name xml:lang="cs">Petr Kovář</Name>
                        <StudentCode>kovpe</StudentCode>
					</Student>
				</BelongsTo>
			</Class>
		</BelongingClass>
	</Timetable>
	
	<Timetable ID="http://example.org/data/timetables/21226B10">
		<AcademicalYear>2021/2022</AcademicalYear>
		<TimetableVersion>1.0</TimetableVersion>
		<PlannedLesson>
			<Lesson ID="http://example.org/data/lessons/MO0800S7">
				<ZoomURI>https://zoom.com/MO0800S7</ZoomURI>
				<LessonCode>MO0800S7</LessonCode>
			</Lesson>
			<Lesson ID="http://example.org/data/lessons/FR1000S6">
				<ZoomURI>https://zoom.com/FR1000S6</ZoomURI>
				<LessonCode>FR1000S6</LessonCode>
			</Lesson>
		</PlannedLesson>
		<BelongingClass>
			<Class ID="http://example.org/data/classes/6B">
				<ClassYear>6</ClassYear>
              	<ClassCode>B</ClassCode>
				<BelongsTo>
				<Student ID="http://example.org/data/students/kliji">
					<Name xml:lang="cs">Jiří Klimošek</Name>
                    <StudentCode>kliji</StudentCode>
					<Nickname xml:lang="cs">Limoš</Nickname>
				</Student>
				</BelongsTo>
			</Class>
		</BelongingClass>
	</Timetable>
	
	<Timetable ID="http://example.org/data/timetables/22234C20">
		<AcademicalYear>2022/2023</AcademicalYear>
		<TimetableVersion>2.0</TimetableVersion>
		<PlannedLesson>
			<Lesson ID="http://example.org/data/lessons/FR1000S9">
				<ZoomURI>https://zoom.com/FR1000S9</ZoomURI>
				<LessonCode>FR1000S9</LessonCode>
			</Lesson>
		</PlannedLesson>
		<BelongingClass>
			<Class ID="http://example.org/data/classes/4C">
                <ClassYear>4</ClassYear>
				<ClassCode>C</ClassCode>
				<BelongsTo>
				<Student ID="http://example.org/data/students/novpa">
					<Name xml:lang="cs">Pavel Novák</Name>
                  	<StudentCode>novpa</StudentCode>
					<Nickname xml:lang="cs">Kajak</Nickname>
					<Nickname xml:lang="cs">Bizon</Nickname>
                  
				</Student>
				</BelongsTo>
			</Class>
		</BelongingClass>
	</Timetable>
</Timetables>
